# Generated by Django 5.0.6 on 2024-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='legal_face',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='logo_link',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='logo_photo',
        ),
        migrations.AddField(
            model_name='geodata',
            name='entity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geodata',
            name='logo',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geodata',
            name='brand',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='nds',
            field=models.BooleanField(verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='status',
            field=models.BooleanField(verbose_name='Статус работы'),
        ),
    ]
