# Generated by Django 5.0.6 on 2024-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0002_remove_geodata_legal_face_remove_geodata_logo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='region',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
