# Generated by Django 5.0.6 on 2024-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0004_remove_geodata_entity_geodata_legal_face_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='legal_face',
        ),
        migrations.AddField(
            model_name='geodata',
            name='entity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='brand',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='legalface',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
