# Generated by Django 5.0.6 on 2024-06-03 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0005_remove_geodata_legal_face_geodata_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='entity',
        ),
        migrations.AddField(
            model_name='geodata',
            name='legal_face',
            field=models.ForeignKey(default=24356879886354265, on_delete=django.db.models.deletion.CASCADE, related_name='geo_data', to='partner_map.legalface', verbose_name='Юридическое лицо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_data', to='partner_map.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalface',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
