# Generated by Django 5.0.6 on 2024-06-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0006_remove_geodata_entity_geodata_legal_face_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodata',
            old_name='legal_face',
            new_name='entity',
        ),
    ]
