# Generated by Django 5.0.6 on 2024-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0011_bonus_id_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='accrual_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
