# Generated by Django 5.0.6 on 2024-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0012_bonus_accrual_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='accrual_value',
        ),
        migrations.AddField(
            model_name='bonus',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
