# Generated by Django 5.0.6 on 2024-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_map', '0013_remove_bonus_accrual_value_bonus_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='nomenclature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номенклатура'),
        ),
    ]
